name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: brian-rose/cookbook-actions/.github/workflows/build-book.yaml@myst-defaults
    with:
      artifact_name: book-zip-${{ github.event.number }}
      base_url: '/${{ github.event.repository.name }}/_preview/${{ github.event.number }}'
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
